# Stage 1: Build the Java application using Maven
FROM maven:3.9.11-eclipse-temurin-25-alpine AS build
WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline
COPY src ./src
RUN mvn clean install -DskipTests

# Stage 2: Create the final, smaller runtime image
FROM eclipse-temurin:25-jre-alpine
WORKDIR /app
COPY --from=build /app/target/*.jar tracker-api.jar
ENTRYPOINT ["java", "-jar", "tracker-api.jar"]
EXPOSE 7070

